Repository proLmpa/NBC_Twogether, pull requests merged in 2023-09, with the labels that each got.

#109 [fix] requestDto에 @NoArgsConstructor 생성자 추가
  src/main/java/com/example/twogether/board/dto/BoardRequestDto.java
  src/main/java/com/example/twogether/user/dto/SignupRequestDto.java
  src/main/java/com/example/twogether/workspace/dto/WpRequestDto.java
Labels: bug, hotfix

#112 [feature] 카드페이지 및 카드 보관/복구, 삭제 구현
  src/main/java/com/example/twogether/card/controller/CardController.java
  src/main/java/com/example/twogether/card/dto/CardResponseDto.java
  src/main/java/com/example/twogether/card/entity/Card.java
  src/main/resources/static/css/board.css
  src/main/resources/static/js/board.js
Labels: feature, frontend

#111 [feature] Redis 포함된 CI 환경 구축
  .github/workflows/twogether-CD.yml
  .github/workflows/twogether-CI.yml
  appspec.yml
  build.gradle
  scripts/deploy.sh
  src/main/java/com/example/twogether/card/controller/CardController.java
  src/main/java/com/example/twogether/card/dto/CardResponseDto.java
  src/main/java/com/example/twogether/checklist/entity/CheckList.java
  src/main/java/com/example/twogether/checklist/entity/CheckListItem.java
  src/main/java/com/example/twogether/common/config/RedisConfig.java
  src/main/java/com/example/twogether/common/config/WebSecurityConfig.java
  src/main/java/com/example/twogether/common/error/CustomErrorCode.java
  src/main/java/com/example/twogether/common/jwt/JwtUtil.java
  src/main/java/com/example/twogether/common/redis/RedisEmail.java
  src/main/java/com/example/twogether/common/redis/RedisRefreshToken.java
  src/main/java/com/example/twogether/common/security/JwtAuthenticationFilter.java
  src/main/java/com/example/twogether/common/security/JwtAuthorizationFilter.java
  src/main/java/com/example/twogether/common/security/UserDetailsServiceImpl.java
  src/main/java/com/example/twogether/mail/config/MailConfig.java
  src/main/java/com/example/twogether/mail/controller/EmailCerificationController.java
  src/main/java/com/example/twogether/mail/dto/EmailCerificationRequstDto.java
  src/main/java/com/example/twogether/mail/service/EmailCerificationService.java
  src/main/java/com/example/twogether/user/controller/UserController.java
  src/main/java/com/example/twogether/user/dto/EditPasswordRequestDto.java
  src/main/java/com/example/twogether/user/dto/EditUserRequestDto.java
  src/main/java/com/example/twogether/user/entity/User.java
  src/main/java/com/example/twogether/user/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/static/js/board.js
  src/main/resources/static/js/signup.js
  src/main/resources/static/js/workspace.js
  src/test/java/com/example/twogether/user/controller/UserControllerTest.java
  src/test/java/com/example/twogether/user/service/UserServiceTest.java
  src/test/resources/application.yml
  src/test/resources/db/h2/data.sql
Labels: CI, test

#117 [feature] 프론트 페이지 기능 구현
  src/main/resources/static/css/board.css
  src/main/resources/static/css/login.css
  src/main/resources/static/css/signup.css
  src/main/resources/static/css/workspace.css
  src/main/resources/static/js/board.js
  src/main/resources/static/js/workspace.js
  src/main/resources/templates/board.html
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
  src/main/resources/templates/workspace.html
Labels: feature, frontend

#118 [feature] AWS CodeDeploy 테스트
  .github/workflows/twogether-CD.yml
  appspec.yml
  build.gradle
  scripts/deploy.sh
  scripts/start.sh
  scripts/stop.sh
  src/main/java/com/example/twogether/common/config/WebSecurityConfig.java
  src/main/java/com/example/twogether/common/controller/ViewController.java
  src/main/java/com/example/twogether/common/jwt/JwtUtil.java
  src/main/java/com/example/twogether/common/security/JwtAuthorizationFilter.java
  src/main/java/com/example/twogether/socialLogin/controller/SocialLonginController.java
  src/main/java/com/example/twogether/socialLogin/service/KakaoLoginService.java
  src/main/java/com/example/twogether/socialLogin/service/NaverLoginService.java
  src/main/resources/static/js/board.js
  src/main/resources/static/js/login.js
  src/main/resources/static/js/signup.js
  src/main/resources/static/js/workspace.js
Labels: CD

#126 [hotfix] 드래그&드랍 버그 수정 및 편의성 개선, 알람 활성화 기능 버그 수정
  src/main/resources/static/css/board.css
  src/main/resources/static/css/header.css
  src/main/resources/static/js/alarm.js
  src/main/resources/static/js/board.js
Labels: frontend

#129 [refactor] 리팩토링 및 AWS 배포를 위한 PR
  src/main/resources/static/css/header.css
  src/main/resources/static/js/alarm.js
  src/main/resources/static/js/board.js
  src/main/resources/static/js/profile.js
  src/main/resources/static/js/workspace.js
  src/main/resources/templates/board.html
  src/main/resources/templates/workspace.html
Labels: CD

#131 [update] 보드 협업자 초대, 알림 로직 리팩토링
  src/main/java/com/example/twogether/alarm/event/CardEditedDueEvent.java
  src/main/java/com/example/twogether/board/service/BoardColService.java
  src/main/java/com/example/twogether/workspace/service/WpColService.java
  src/main/resources/static/css/board.css
  src/main/resources/static/css/header.css
  src/main/resources/static/js/alarm.js
  src/main/resources/templates/board.html
Labels: feature, refactor, frontend
