Repository proLmpa/NBC_Twogether, pull requests merged in 2023-08, with the labels that each got.

#24 [hotfix] linkedlist가 순수 필드값이여서 parentId가 제대로 적용되지 않음.
  src/main/java/com/example/twogether/deck/controller/DeckController.java
  src/main/java/com/example/twogether/deck/dto/MoveDeckRequestDto.java
  src/main/java/com/example/twogether/deck/entity/Deck.java
  src/main/java/com/example/twogether/deck/entity/DeckManager.java
  src/main/java/com/example/twogether/deck/repository/DeckRepository.java
  src/main/java/com/example/twogether/deck/service/DeckService.java
Labels: enhancement

#36 [fix] 현재까지 완성한 도메인 entity 간의 연관 관계 정리
  .gitignore
  src/main/java/com/example/twogether/board/entity/Board.java
  src/main/java/com/example/twogether/board/entity/BoardMember.java
  src/main/java/com/example/twogether/board/repository/BoardMemberRepository.java
  src/main/java/com/example/twogether/board/repository/BoardRepository.java
  src/main/java/com/example/twogether/deck/entity/Deck.java
  src/main/java/com/example/twogether/deck/service/DeckService.java
  src/main/java/com/example/twogether/workspace/entity/Workspace.java
Labels: bug, enhancement

#45 [update] 머지 과정에서 생긴 에러 처리
  src/main/java/com/example/twogether/common/error/CustomErrorCode.java
  src/main/java/com/example/twogether/deck/service/DeckService.java
  src/main/java/com/example/twogether/workspace/entity/WorkspaceMember.java
Labels: bug, hotfix

#52 [feature] 카드 추가 기능 구현
  src/main/java/com/example/twogether/Card/controller/CardController.java
  src/main/java/com/example/twogether/Card/entity/Card.java
  src/main/java/com/example/twogether/Card/service/CardService.java
  src/main/java/com/example/twogether/common/error/CustomErrorCode.java
Labels: feature, refactor

#53 [feature] 라벨 CRUD 기능 구현
  src/main/java/com/example/twogether/common/config/WebSecurityConfig.java
  src/main/java/com/example/twogether/common/error/CustomErrorCode.java
  src/main/java/com/example/twogether/label/controller/LabelController.java
  src/main/java/com/example/twogether/label/dto/LabelRequestDto.java
  src/main/java/com/example/twogether/label/dto/LabelResponseDto.java
  src/main/java/com/example/twogether/label/entity/Label.java
  src/main/java/com/example/twogether/label/repository/LabelRepository.java
  src/main/java/com/example/twogether/label/service/LabelService.java
Labels: feature

#54 [feature] 카드 이동 기능 구현
  src/main/java/com/example/twogether/Card/controller/CardController.java
  src/main/java/com/example/twogether/Card/dto/CardEditRequestDto.java
  src/main/java/com/example/twogether/Card/dto/CardResponseDto.java
  src/main/java/com/example/twogether/Card/dto/MoveCardRequestDto.java
  src/main/java/com/example/twogether/Card/entity/Card.java
  src/main/java/com/example/twogether/Card/service/CardService.java
  src/main/java/com/example/twogether/deck/dto/DeckResponseDto.java
  src/main/java/com/example/twogether/deck/entity/Deck.java
Labels: enhancement, feature

#41 [update] 워크스페이스, 보드 수정 및 협업자 기능 구현
  src/main/java/com/example/twogether/TwogetherApplication.java
  src/main/java/com/example/twogether/board/controller/BoardColController.java
  src/main/java/com/example/twogether/board/controller/BoardController.java
  src/main/java/com/example/twogether/board/controller/BoardMemberController.java
  src/main/java/com/example/twogether/board/dto/BoardColRequestDto.java
  src/main/java/com/example/twogether/board/dto/BoardColResponseDto.java
  src/main/java/com/example/twogether/board/dto/BoardCollaboRequestDto.java
  src/main/java/com/example/twogether/board/dto/BoardRequestDto.java
  src/main/java/com/example/twogether/board/dto/BoardResponseDto.java
  src/main/java/com/example/twogether/board/dto/BoardsResponseDto.java
  src/main/java/com/example/twogether/board/entity/Board.java
  src/main/java/com/example/twogether/board/entity/BoardCollaborator.java
  src/main/java/com/example/twogether/board/repository/BoardColRepository.java
  src/main/java/com/example/twogether/board/repository/BoardMemberRepository.java
  src/main/java/com/example/twogether/board/repository/BoardRepository.java
  src/main/java/com/example/twogether/board/service/BoardColService.java
  src/main/java/com/example/twogether/board/service/BoardMemberService.java
  src/main/java/com/example/twogether/board/service/BoardService.java
  src/main/java/com/example/twogether/card/controller/CardController.java
  src/main/java/com/example/twogether/card/dto/CardEditRequestDto.java
  src/main/java/com/example/twogether/card/dto/CardResponseDto.java
  src/main/java/com/example/twogether/card/dto/MoveCardRequestDto.java
  src/main/java/com/example/twogether/card/entity/Card.java
  src/main/java/com/example/twogether/card/repository/CardRepository.java
  src/main/java/com/example/twogether/card/service/CardService.java
  src/main/java/com/example/twogether/common/config/WebSecurityConfig.java
  src/main/java/com/example/twogether/common/error/CustomErrorCode.java
  src/main/java/com/example/twogether/deck/dto/DeckResponseDto.java
  src/main/java/com/example/twogether/deck/entity/Deck.java
  src/main/java/com/example/twogether/user/controller/UserController.java
  src/main/java/com/example/twogether/user/entity/User.java
  src/main/java/com/example/twogether/user/repository/UserRepository.java
  src/main/java/com/example/twogether/workspace/controller/WorkspaceController.java
  src/main/java/com/example/twogether/workspace/controller/WorkspaceMemberController.java
  src/main/java/com/example/twogether/workspace/controller/WpColController.java
  src/main/java/com/example/twogether/workspace/controller/WpController.java
  src/main/java/com/example/twogether/workspace/dto/WorkspaceMemberRequestDto.java
  src/main/java/com/example/twogether/workspace/dto/WorkspaceMemberResponseDto.java
  src/main/java/com/example/twogether/workspace/dto/WorkspaceResponseDto.java
  src/main/java/com/example/twogether/workspace/dto/WpColRequestDto.java
  src/main/java/com/example/twogether/workspace/dto/WpColResponseDto.java
  src/main/java/com/example/twogether/workspace/dto/WpRequestDto.java
  src/main/java/com/example/twogether/workspace/dto/WpResponseDto.java
  src/main/java/com/example/twogether/workspace/dto/WpsResponseDto.java
  src/main/java/com/example/twogether/workspace/entity/Workspace.java
  src/main/java/com/example/twogether/workspace/entity/WorkspaceCollaborator.java
  src/main/java/com/example/twogether/workspace/repository/WorkspaceMemberRepository.java
  src/main/java/com/example/twogether/workspace/repository/WpColRepository.java
  src/main/java/com/example/twogether/workspace/repository/WpRepository.java
  src/main/java/com/example/twogether/workspace/service/WorkspaceMemberService.java
  src/main/java/com/example/twogether/workspace/service/WorkspaceService.java
  src/main/java/com/example/twogether/workspace/service/WpColService.java
  src/main/java/com/example/twogether/workspace/service/WpService.java
Labels: enhancement, feature

#57 [feature] Card에 이미지, 동영상 첨부 기능
  .gitignore
  build.gradle
  src/main/java/com/example/twogether/card/controller/CardController.java
  src/main/java/com/example/twogether/card/entity/Card.java
  src/main/java/com/example/twogether/card/service/CardService.java
  src/main/java/com/example/twogether/common/error/CustomErrorCode.java
  src/main/java/com/example/twogether/common/s3/AwsS3Config.java
  src/main/java/com/example/twogether/common/s3/S3Uploader.java
  src/main/resources/application.properties
Labels: enhancement

#61 [update] 보드에서 덱 조회
  src/main/java/com/example/twogether/board/dto/BoardResponseDto.java
Labels: enhancement

#65 [feature] Card-Label 매핑 후 CRD 구현
  src/main/java/com/example/twogether/card/controller/CardLabelController.java
  src/main/java/com/example/twogether/card/entity/Card.java
  src/main/java/com/example/twogether/card/entity/CardLabel.java
  src/main/java/com/example/twogether/card/repository/CardLabelRepository.java
  src/main/java/com/example/twogether/card/service/CardLabelService.java
  src/main/java/com/example/twogether/card/service/CardService.java
  src/main/java/com/example/twogether/common/config/WebSecurityConfig.java
  src/main/java/com/example/twogether/common/error/CustomErrorCode.java
  src/main/java/com/example/twogether/label/controller/LabelController.java
  src/main/java/com/example/twogether/label/service/LabelService.java
  src/main/java/com/example/twogether/workspace/dto/WpColRequestDto.java
  src/main/java/com/example/twogether/workspace/service/WpColService.java
Labels: enhancement, feature

#60 [feature] 카드 마감일 지정
  src/main/java/com/example/twogether/card/controller/CardController.java
  src/main/java/com/example/twogether/card/dto/CardResponseDto.java
  src/main/java/com/example/twogether/card/dto/DateRequestDto.java
  src/main/java/com/example/twogether/card/entity/Card.java
  src/main/java/com/example/twogether/card/service/CardService.java
  src/main/java/com/example/twogether/common/s3/S3Uploader.java
Labels: feature

#67 [feature] 댓글 CRUD 구현
  src/main/java/com/example/twogether/board/repository/BoardColRepository.java
  src/main/java/com/example/twogether/board/service/BoardColService.java
  src/main/java/com/example/twogether/card/dto/CardResponseDto.java
  src/main/java/com/example/twogether/card/dto/DateRequestDto.java
  src/main/java/com/example/twogether/card/entity/Card.java
  src/main/java/com/example/twogether/card/service/CardService.java
  src/main/java/com/example/twogether/comment/controller/CommentController.java
  src/main/java/com/example/twogether/comment/dto/CommentRequestDto.java
  src/main/java/com/example/twogether/comment/dto/CommentResponseDto.java
  src/main/java/com/example/twogether/comment/entity/Comment.java
  src/main/java/com/example/twogether/comment/repository/CommentRepository.java
  src/main/java/com/example/twogether/comment/service/CommentService.java
  src/main/java/com/example/twogether/common/config/WebSecurityConfig.java
  src/main/java/com/example/twogether/common/error/CustomErrorCode.java
  src/main/java/com/example/twogether/user/entity/User.java
Labels: feature

#70 [feature] 체크리스트 CRUD 기능 구현
  src/main/java/com/example/twogether/card/entity/Card.java
  src/main/java/com/example/twogether/checklist/controller/CheckListController.java
  src/main/java/com/example/twogether/checklist/dto/CheckListRequestDto.java
  src/main/java/com/example/twogether/checklist/dto/CheckListResponseDto.java
  src/main/java/com/example/twogether/checklist/entity/CheckList.java
  src/main/java/com/example/twogether/checklist/repository/CheckListRepository.java
  src/main/java/com/example/twogether/checklist/service/CheckListService.java
  src/main/java/com/example/twogether/common/error/CustomErrorCode.java
Labels: feature

#71 [update] 협업자로 초대된 워크스페이스, 보드 조회 기능 구현
  src/main/java/com/example/twogether/board/controller/BoardColController.java
  src/main/java/com/example/twogether/board/controller/BoardController.java
  src/main/java/com/example/twogether/board/dto/BoardResponseDto.java
  src/main/java/com/example/twogether/board/repository/BoardColRepository.java
  src/main/java/com/example/twogether/board/repository/BoardRepository.java
  src/main/java/com/example/twogether/board/service/BoardColService.java
  src/main/java/com/example/twogether/common/error/CustomErrorCode.java
  src/main/java/com/example/twogether/user/repository/UserRepository.java
  src/main/java/com/example/twogether/workspace/controller/WpColController.java
  src/main/java/com/example/twogether/workspace/controller/WpController.java
  src/main/java/com/example/twogether/workspace/dto/WpColRequestDto.java
  src/main/java/com/example/twogether/workspace/dto/WpColResponseDto.java
  src/main/java/com/example/twogether/workspace/dto/WpColWpResponseDto.java
  src/main/java/com/example/twogether/workspace/dto/WpResponseDto.java
  src/main/java/com/example/twogether/workspace/entity/Workspace.java
  src/main/java/com/example/twogether/workspace/entity/WorkspaceCollaborator.java
  src/main/java/com/example/twogether/workspace/entity/WpColWp.java
  src/main/java/com/example/twogether/workspace/entity/WpColWpId.java
  src/main/java/com/example/twogether/workspace/repository/WpColRepository.java
  src/main/java/com/example/twogether/workspace/repository/WpColWpRepository.java
  src/main/java/com/example/twogether/workspace/repository/WpRepository.java
  src/main/java/com/example/twogether/workspace/service/WpColService.java
  src/main/java/com/example/twogether/workspace/service/WpService.java
  src/main/resources/application.properties
Labels: enhancement

#79 [test] User Controller & Service 테스트 코드 작성 후 깃헙 액션 CI 환경 적용
  .github/workflows/twogether-CI.yml
  build.gradle
  src/main/java/com/example/twogether/TwogetherApplication.java
  src/main/java/com/example/twogether/common/error/CustomErrorCode.java
  src/main/java/com/example/twogether/user/controller/UserController.java
  src/main/java/com/example/twogether/user/dto/EditUserRequestDto.java
  src/main/java/com/example/twogether/user/dto/UserResponseDto.java
  src/main/java/com/example/twogether/user/entity/User.java
  src/test/java/com/example/twogether/user/controller/UserControllerTest.java
  src/test/java/com/example/twogether/user/service/UserServiceTest.java
  src/test/resources/application-test.yml
  src/test/resources/application.yml
Labels: CI

#87 [Complete] 테스트코드 작성
  build.gradle
  src/main/java/com/example/twogether/card/dto/DateRequestDto.java
  src/main/java/com/example/twogether/card/dto/MoveCardRequestDto.java
  src/main/java/com/example/twogether/deck/dto/MoveDeckRequestDto.java
  src/test/java/com/example/twogether/card/service/CardServiceTest.java
  src/test/java/com/example/twogether/deck/service/DeckServiceTest.java
  src/test/resources/application-test.yml
  src/test/resources/db/h2/data.sql
Labels: CI, test

#89 [feature] 단일 서버에서 프론트엔드 회원가입/로그인 기능 구현하기
  build.gradle
  src/main/java/com/example/twogether/board/repository/BoardColRepository.java
  src/main/java/com/example/twogether/board/repository/BoardRepository.java
  src/main/java/com/example/twogether/card/repository/CardColRepository.java
  src/main/java/com/example/twogether/common/config/WebSecurityConfig.java
  src/main/java/com/example/twogether/common/controller/ViewController.java
  src/main/java/com/example/twogether/common/dto/ErrorResponseDto.java
  src/main/java/com/example/twogether/common/exception/GlobalControllerAdvice.java
  src/main/java/com/example/twogether/deck/repository/DeckRepository.java
  src/main/java/com/example/twogether/user/repository/UserRepository.java
  src/main/resources/static/css/login.css
  src/main/resources/static/css/signup.css
  src/main/resources/static/js/login.js
  src/main/resources/static/js/signup.js
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
Labels: feature

#88 [feature] 테스트코드 작성
  src/main/java/com/example/twogether/board/dto/BoardRequestDto.java
  src/main/java/com/example/twogether/workspace/service/WpService.java
  src/test/java/com/example/twogether/board/service/BoardServiceTest.java
  src/test/java/com/example/twogether/workspace/service/WpServiceTest.java
Labels: CI, test
